---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26
ratings %>% ggplot(aes(x=rating)) + geom_histogram()
```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group
ratings %>% group_by(movie_id) %>% summarize(count = n(), mean_ratings = mean(rating))
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
ratings %>% group_by(movie_id) %>% summarize(count = n()) %>% ggplot(aes(x=count)) + geom_histogram() + scale_x_log10()
# hint: try scale_x_log10() for a logarithmic x axis
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density
ratings %>% group_by(movie_id) %>% summarize(mean_ratings = mean(rating)) %>% ggplot(aes(x = mean_ratings)) + geom_histogram()

ratings %>% group_by(movie_id) %>% summarize(mean_ratings = mean(rating)) %>% ggplot(aes(x = mean_ratings)) + geom_density()

```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below
movie_rank <- ratings %>% group_by(movie_id) %>% summarize(count = n()) %>% arrange(desc(count)) %>% mutate(cum_sum = rank(cumsum(count/1000)), density = cumsum(count/sum(count)) * 100)

# plot the CDF of movie popularity
movie_rank %>% ggplot(aes(cum_sum, y = density)) + geom_line() + xlab("Movie Rank") + ylab("CDF")
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
ratings %>% group_by(user_id) %>% summarize(count = n(), mean_ratings = mean(rating))
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
ratings %>% group_by(user_id) %>% summarize(count = n())%>% ggplot(aes(x=user_id)) + geom_density() + scale_x_log10()
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).
ratings %>% group_by(user_id) %>% summarize(count = n()) %>% filter(user_id >=10) %>% mutate(cum_sum = rank(cumsum(count)/1000), inventory = cumsum(count)) %>% ggplot(aes(x = inventory , y= cum_sum )) + geom_line() + xlab("Inventory size") + ylab("Percentage of Users Satisfied")

ratings %>% group_by(user_id) %>% summarize(count = n()) %>% filter(user_id >=10) %>% mutate(cum_sum = rank(cumsum(count/1000)), inventory = rank(cumsum(count))) %>% ggplot(aes(x = inventory , y= cum_sum )) + geom_line() + xlab("Inventory size") + ylab("Percentage of Users Satisfied")


```
