---
title: "test_citibike_predictions"
author: "Iman Abakoyas (Lehman College)"
date: "6/21/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(scales)
library(lubridate)
library(modelr)
theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)
```

##

```{r cars}
load('trips_2015.RData')
load('citibike.RData')

holiday <- read_csv("US Bank holidays.csv", col_names = c('num','ymd','holiday'))

trips_per_day_2015 <- trips_per_day_2015 %>% left_join(holiday, by = "ymd") %>% mutate(tmax = tmax/10, tmin = tmin/10, weekday = as.factor(wday(ymd)), is_weekend = (weekday == 1 | weekday == 7), is_holiday = !is.na(holiday), prcp_level = as.numeric(prcp >= 0.3))

```

## 

```{r pressure, echo=FALSE}
model_test <- lm(formula = num_trips ~ poly(tmin, 4, raw = T) + poly(tmax, 4, raw = T) + poly(snwd, 4, raw = T) + weekday + prcp_level + 
    is_weekend + is_holiday, data = trips_per_day_2015)

summary(model_test)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
rmse(model_test, trips_per_day_2015)
```


```{r}
trips_test_2015 <- trips_per_day_2015 %>% add_predictions(model_test) %>% mutate(split = "test")

trips_test_2015 %>% ggplot(aes(x = ymd, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Date') +
  ylab('Daily trips') +
  scale_y_continuous()

trips_test_2015 %>% ggplot(aes(x = pred, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Predicted') +
  ylab('Actual') +
  scale_y_continuous()
```
